### ISSUE TITLE
Throws error "Results object was not created from this ESLint instance." after eslint executes properly

### ISSUE THREAD

**Issue by JessicaSachs** [CatChen/eslint-suggestion-action#1689]
### Description

I setup the GitHub action pretty simply. I'm running Node 22 with pnpm. I checkout the repository, install dependencies, and run your action. That's it.

I'm trying to find a workaround, but the bin paths look correct. I just don't know what else is resolving to the deeply nested pnpm dependency. `pnpm which` spits out the same location as the `eslint-lib-path` and `eslint-bin-path`.

### Details

It seems like this line is what's throwing

https://github.com/CatChen/eslint-suggestion-action/blob/e39bfd688787d413f36b354d5b4960e2ac6c6279/src/index.ts#L50C16-L50C38

### Configuration

```
Run CatChen/eslint-suggestion-action@v2
  with:
    request-changes: true
    fail-check: false
    github-token: ***
    directory: ./
    targets: .
    eslint-lib-path: ./node_modules/eslint/lib/api.js
    eslint-bin-path: ./node_modules/.bin/eslint
  env:
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
```

### Full Logs Below

```
  Working directory is: /home/runner/work/docs/docs
  Working directory is changed to: /home/runner/work/docs/docs
  Notice: Using ESLint from: /home/runner/work/docs/docs/node_modules/eslint/lib/api.js
  Notice: Using ESLint binary from: ./node_modules/.bin/eslint
  /home/runner/work/docs/docs/node_modules/.bin/eslint . --no-error-on-unmatched-pattern --format json
  [{"filePath":"/home/runner/work/docs/docs/app.config.ts","messages":[],"suppressedMessages":[],"errorCount":0,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]},{"filePath":"/home/runner/work/docs/docs/app.vue","messages":[],"suppressedMessages":[],"errorCount":0,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]},{"filePath":"/home/runner/work/docs/docs/components/ui/button/Button.global.vue","messages":[{"ruleId":"vue/require-default-prop","severity":1,"message":"Prop 'variant' requires default value to be set.","line":8,"column":3,"nodeType":"TSPropertySignature","messageId":"missingDefault","endLine":8,"endColumn":38},{"ruleId":"vue/require-default-prop","severity":1,"message":"Prop 'size' requires default value to be set.","line":9,"column":3,"nodeType":"TSPropertySignature","messageId":"missingDefault","endLine":9,"endColumn":3[2](https://github.com/neverendingsupport/docs/actions/runs/11376211642/job/31648300033#step:4:2)},{"ruleId":"vue/require-default-prop","severity":1,"message":"Prop 'class' requires default value to be set.","line":10,"column":[3](https://github.com/neverendingsupport/docs/actions/runs/11376211642/job/31648300033#step:4:3),"nodeType":"TSPropertySignature","messageId":"missingDefault","endLine":10,"endColumn":3[4](https://github.com/neverendingsupport/docs/actions/runs/11376211642/job/31648300033#step:4:4)}],"suppressedMessages":[],"errorCount":0,"fatalErrorCount":0,"warningCount":3,"fixableErrorCount":0,"fixableWarningCount":0,"source":"<script setup lang=\"ts\">\nimport type { HTMLAttributes } from 'vue'\nimport { Primitive, type PrimitiveProps } from 'radix-vue'\nimport { type ButtonVariants, buttonVariants } from '.'\nimport { cn } from '@/lib/utils'\n\ninterface Props extends PrimitiveProps {\n  variant?: ButtonVariants['variant']\n  size?: ButtonVariants['size']\n  class?: HTMLAttributes['class']\n}\n\nconst props = withDefaults(defineProps<Props>(), {\n})\n</script>\n\n<template>\n  <Primitive :as=\"as\" :as-child=\"asChild\" :class=\"cn(buttonVariants({ variant, size }), props.class)\">\n    <slot />\n  </Primitive>\n</template>\n","usedDeprecatedRules":[]},{"filePath":"/home/runner/work/docs/docs/components/ui/button/index.ts","messages":[],"suppressedMessages":[],"errorCount":0,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]},{"filePath":"/home/runner/work/docs/docs/components/ui/toast/Toast.vue","messages":[],"suppressedMessages":[],"errorCount":0,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]},{"filePath":"/home/runner/work/docs/docs/components/ui/toast/ToastAction.vue","messages":[],"suppressedMessages":[],"errorCount":0,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]},{"filePath":"/home/runner/work/docs/docs/components/ui/toast/ToastClose.vue","messages":[],"suppressedMessages":[],"errorCount":0,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]},{"filePath":"/home/runner/work/docs/docs/components/ui/toast/ToastDescription.vue","messages":[],"suppressedMessages":[],"errorCount":0,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]},{"filePath":"/home/runner/work/docs/docs/components/ui/toast/ToastProvider.vue","messages":[],"suppressedMessages":[],"errorCount":0,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]},{"filePath":"/home/runner/work/docs/docs/components/ui/toast/ToastTitle.vue","messages":[],"suppressedMessages":[],"errorCount":0,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]},{"filePath":"/home/runner/work/docs/docs/components/ui/toast/ToastViewport.vue","messages":[],"suppressedMessages":[],"errorCount":0,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]},{"filePath":"/home/runner/work/docs/docs/components/ui/toast/Toaster.vue","messages":[],"suppressedMessages":[],"errorCount":0,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]},{"filePath":"/home/runner/work/docs/docs/components/ui/toast/index.ts","messages":[],"suppressedMessages":[],"errorCount":0,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]},{"filePath":"/home/runner/work/docs/docs/components/ui/toast/use-toast.ts","messages":[],"suppressedMessages":[],"errorCount":0,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]},{"filePath":"/home/runner/work/docs/docs/eslint.config.mjs","messages":[],"suppressedMessages":[],"errorCount":0,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]},{"filePath":"/home/runner/work/docs/docs/lib/utils.ts","messages":[],"suppressedMessages":[],"errorCount":0,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]},{"filePath":"/home/runner/work/docs/docs/nuxt.config.ts","messages":[],"suppressedMessages":[],"errorCount":0,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]},{"filePath":"/home/runner/work/docs/docs/pages/404.vue","messages":[],"suppressedMessages":[],"errorCount":0,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]},{"filePath":"/home/runner/work/docs/docs/pages/[...slug].vue","messages":[],"suppressedMessages":[],"errorCount":0,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]},{"filePath":"/home/runner/work/docs/docs/pages/index.vue","messages":[],"suppressedMessages":[],"errorCount":0,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]},{"filePath":"/home/runner/work/docs/docs/tailwind.config.js","messages":[],"suppressedMessages":[],"errorCount":0,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]}]
  ESLint exit code: 0
  File name: app.config.ts
  File name: app.vue
  File name: components/ui/button/Button.global.vue
    [1] Prop 'variant' requires default value to be set. @ 8
    [1] Prop 'size' requires default value to be set. @ 9
    [1] Prop 'class' requires default value to be set. @ 10
  File name: components/ui/button/index.ts
  File name: components/ui/toast/Toast.vue
  File name: components/ui/toast/ToastAction.vue
  File name: components/ui/toast/ToastClose.vue
  File name: components/ui/toast/ToastDescription.vue
  File name: components/ui/toast/ToastProvider.vue
  File name: components/ui/toast/ToastTitle.vue
  File name: components/ui/toast/ToastViewport.vue
  File name: components/ui/toast/Toaster.vue
  File name: components/ui/toast/index.ts
  File name: components/ui/toast/use-toast.ts
  File name: eslint.config.mjs
  File name: lib/utils.ts
  File name: nuxt.config.ts
  File name: pages/404.vue
  File name: pages/[...slug].vue
  File name: pages/index.vue
  File name: tailwind.config.js
  
  /home/runner/work/docs/docs/node_modules/.pnpm/eslint@9.12.0_jiti@2.3.3/node_modules/eslint/lib/eslint/eslint.js:399
      return new TypeError("Results object was not created from this ESLint instance.");
             ^
  TypeError: Results object was not created from this ESLint instance.
      at createExtraneousResultsError (/home/runner/work/docs/docs/node_modules/.pnpm/eslint@9.12.0_jiti@2.3.3/node_modules/eslint/lib/eslint/eslint.js:399:12)
      at ESLint.getRulesMetaForResults (/home/runner/work/docs/docs/node_modules/.pnpm/eslint@9.12.0_jiti@2.3.3/node_modules/eslint/lib/eslint/eslint.js:621:27)
      at file:///home/runner/work/_actions/CatChen/eslint-suggestion-action/v2/webpack:/eslint-suggestion-action/src/index.ts:48:1
      at Generator.next (<anonymous>)
      at fulfilled (file:///home/runner/work/_actions/CatChen/eslint-suggestion-action/v2/webpack:/eslint-suggestion-action/src/index.ts:[5](https://github.com/neverendingsupport/docs/actions/runs/11376211642/job/31648300033#step:4:5):1)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by JessicaSachs** [comment]
This is only an issue with v2, which the README references.
