### ISSUE TITLE
Can't run the action because: `HttpError: Not Found`

### ISSUE THREAD

**Issue by wolverian** [CatChen/eslint-suggestion-action#883]
I'm getting the following error running this action:

```
HttpError: Not Found
     at file:///home/runner/work/_actions/CatChen/eslint-suggestion-action/v2/webpack:/eslint-suggestion-action/node_modules/@octokit/request/dist-node/index.js:86:1
```

Full debug log of the action run follows:

<details><summary>Debug log</summary>
<p>

```log
2024-02-18T14:36:45.8405551Z ##[debug]Evaluating condition for step: 'Run CatChen/eslint-suggestion-action@v2'
2024-02-18T14:36:45.8408183Z ##[debug]Evaluating: success()
2024-02-18T14:36:45.8408860Z ##[debug]Evaluating success:
2024-02-18T14:36:45.8409613Z ##[debug]=> true
2024-02-18T14:36:45.8410182Z ##[debug]Result: true
2024-02-18T14:36:45.8411094Z ##[debug]Starting: Run CatChen/eslint-suggestion-action@v2
2024-02-18T14:36:45.8452874Z ##[debug]Loading inputs
2024-02-18T14:36:45.8455700Z ##[debug]Evaluating: github.token
2024-02-18T14:36:45.8456215Z ##[debug]Evaluating Index:
2024-02-18T14:36:45.8456649Z ##[debug]..Evaluating github:
2024-02-18T14:36:45.8457112Z ##[debug]..=> Object
2024-02-18T14:36:45.8457506Z ##[debug]..Evaluating String:
2024-02-18T14:36:45.8457930Z ##[debug]..=> 'token'
2024-02-18T14:36:45.8458708Z ##[debug]=> '***'
2024-02-18T14:36:45.8459284Z ##[debug]Result: '***'
2024-02-18T14:36:45.8464271Z ##[debug]Loading env
2024-02-18T14:36:45.8470837Z ##[group]Run CatChen/eslint-suggestion-action@v2
2024-02-18T14:36:45.8471372Z with:
2024-02-18T14:36:45.8471665Z   fail-check: true
2024-02-18T14:36:45.8472021Z   request-changes: true
2024-02-18T14:36:45.8472648Z   github-token: ***
2024-02-18T14:36:45.8473002Z   directory: ./
2024-02-18T14:36:45.8473330Z   targets: .
2024-02-18T14:36:45.8473735Z   eslint-lib-path: ./node_modules/eslint/lib/api.js
2024-02-18T14:36:45.8474359Z   eslint-bin-path: ./node_modules/.bin/eslint
2024-02-18T14:36:45.8474878Z env:
2024-02-18T14:36:45.8475288Z   MISE_TRUSTED_CONFIG_PATHS: /home/runner/work/bubu/bubu
2024-02-18T14:36:45.8475851Z   MISE_YES: 1
2024-02-18T14:36:45.8476167Z   MISE_EXPERIMENTAL: 1
2024-02-18T14:36:45.8476532Z ##[endgroup]
2024-02-18T14:36:46.0049798Z ::group::ESLint
2024-02-18T14:36:46.0050172Z ##[group]ESLint
2024-02-18T14:36:46.0053245Z Working directory is: /home/runner/work/bubu/bubu
2024-02-18T14:36:46.0054174Z Working directory is changed to: /home/runner/work/bubu/bubu
2024-02-18T14:36:46.0145418Z ##[notice]Using ESLint from: /home/runner/work/bubu/bubu/node_modules/eslint/lib/api.js
2024-02-18T14:36:47.0187242Z ##[notice]Using ESLint binary from: ./node_modules/.bin/eslint
2024-02-18T14:36:47.0373116Z [command]/home/runner/work/bubu/bubu/node_modules/.bin/eslint . --no-error-on-unmatched-pattern --format json
2024-02-18T14:36:48.4710736Z [{"filePath":"/home/runner/work/bubu/bubu/.eslintrc.cjs","messages":[],"suppressedMessages":[],"errorCount":0,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[{"ruleId":"no-extra-semi","replacedBy":[]},{"ruleId":"no-mixed-spaces-and-tabs","replacedBy":[]}]},{"filePath":"/home/runner/work/bubu/bubu/index.ts","messages":[{"ruleId":"@typescript-eslint/no-unused-vars","severity":2,"message":"'server' is defined but never used. Allowed unused args must match /^_/u.","line":4,"column":28,"nodeType":"Identifier","messageId":"unusedVar","endLine":4,"endColumn":42}],"suppressedMessages":[],"errorCount":1,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"source":"import type { Server } from \"bun\";\n\nconst server = Bun.serve({\n  fetch(_request: Request, server: Server): Response | Promise<Response> {\n    return Response.json({ message: \"ok\" });\n  },\n});\n\nconsole.info(`Server running at ${server.url}`);\n","usedDeprecatedRules":[{"ruleId":"no-extra-semi","replacedBy":[]},{"ruleId":"no-mixed-spaces-and-tabs","replacedBy":[]}]}]
2024-02-18T14:36:48.4960603Z ESLint exit code: 1
2024-02-18T14:36:48.4967120Z File name: .eslintrc.cjs
2024-02-18T14:36:48.4970505Z File name: index.ts
2024-02-18T14:36:48.4973981Z   [2] 'server' is defined but never used. Allowed unused args must match /^_/u. @ 4
2024-02-18T14:36:48.5956670Z ::endgroup::
2024-02-18T14:36:48.5957042Z ##[endgroup]
2024-02-18T14:36:48.5960318Z Event name: push
2024-02-18T14:36:48.5966521Z Owner: wolverian
2024-02-18T14:36:48.5969609Z Repo: bubu
2024-02-18T14:36:48.5972504Z Before SHA: 0000000000000000000000000000000000000000
2024-02-18T14:36:48.5975880Z After SHA: a9c18308b31ea8fc1f4b2e930c65ac43e5891f5f
2024-02-18T14:36:48.5984102Z ::group::GitHub Push
2024-02-18T14:36:48.5984499Z ##[group]GitHub Push
2024-02-18T14:37:03.1415043Z HttpError: Not Found
2024-02-18T14:37:03.1416834Z     at file:///home/runner/work/_actions/CatChen/eslint-suggestion-action/v2/webpack:/eslint-suggestion-action/node_modules/@octokit/request/dist-node/index.js:86:1
2024-02-18T14:37:03.1418427Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2024-02-18T14:37:03.1420236Z     at Job.doExecute (file:///home/runner/work/_actions/CatChen/eslint-suggestion-action/v2/webpack:/eslint-suggestion-action/node_modules/bottleneck/light.js:405:1)
2024-02-18T14:37:03.1536200Z ##[debug]Node Action run completed with exit code 1
2024-02-18T14:37:03.1544760Z ##[debug]Finishing: Run CatChen/eslint-suggestion-action@v2
```

</p>
</details>

**Comment by CatChen** [comment]
I suspect the error comes from here:

https://github.com/CatChen/eslint-suggestion-action/blob/8fb7db4e235f7af9fc434349a124034b681d99a3/src/push.ts#L23-L27

Does this error happen if you retry? Does the workflow job have the right permission to fetch metadata about a push?
